### TOURNAMENTS API TESTS

@baseUrl = http://localhost:3142
@contentType = application/json

### Get all tournaments
GET {{baseUrl}}/tournaments
Content-Type: {{contentType}}

###

### Get active tournaments only
GET {{baseUrl}}/tournaments/active
Content-Type: {{contentType}}

###

### Get tournament by ID (detailed view)
GET {{baseUrl}}/tournaments/1
Content-Type: {{contentType}}

###

### Create new tournament
POST {{baseUrl}}/tournaments
Content-Type: {{contentType}}

{
  "name": "Weekend Championship",
  "owner_id": 1
}

###

### Join tournament (user 2 joins tournament 1)
POST {{baseUrl}}/tournaments/1/join
Content-Type: {{contentType}}

{
  "user_id": 2
}

###

### Join tournament (user 3 joins tournament 1)
POST {{baseUrl}}/tournaments/1/join
Content-Type: {{contentType}}

{
  "user_id": 3
}

###

### Join tournament (user 4-9 join tournament 1 to test player limit)
POST {{baseUrl}}/tournaments/1/join
Content-Type: {{contentType}}

{
  "user_id": 4
}
###
POST {{baseUrl}}/tournaments/1/join
Content-Type: {{contentType}}
{
  "user_id": 5
}
###
POST {{baseUrl}}/tournaments/1/join
Content-Type: {{contentType}}
{
  "user_id": 6
}
###
POST {{baseUrl}}/tournaments/1/join
Content-Type: {{contentType}}
{
  "user_id": 7
}
###
POST {{baseUrl}}/tournaments/1/join
Content-Type: {{contentType}}
{
  "user_id": 8
}
###
POST {{baseUrl}}/tournaments/1/join
Content-Type: {{contentType}}
{
  "user_id": 9
}
# This should fail (max 8 players)

###

### Start tournament (should succeed with 2-8 players, fail with >8)
POST {{baseUrl}}/tournaments/1/start
Content-Type: {{contentType}}

###

### Get tournaments for specific user
GET {{baseUrl}}/tournaments/user/1
Content-Type: {{contentType}}

###

### Get tournament details after starting
GET {{baseUrl}}/tournaments/1
Content-Type: {{contentType}}

###

### Get final ranking for tournament 1
GET {{baseUrl}}/tournaments/1/final-ranking
Content-Type: {{contentType}}

###

### Test error cases

### Try to join non-existent tournament
POST {{baseUrl}}/tournaments/999/join
Content-Type: {{contentType}}

{
  "user_id": 1
}

###

### Try to join already ongoing tournament
POST {{baseUrl}}/tournaments/2/join
Content-Type: {{contentType}}

{
  "user_id": 1
}

###

### Try to start tournament with insufficient players
POST {{baseUrl}}/tournaments/3/start
Content-Type: {{contentType}}

###

### Try to start tournament with more than 8 players (should fail)
POST {{baseUrl}}/tournaments/1/start
Content-Type: {{contentType}}
# (Assume >8 players joined above)

###

### Try to create tournament with invalid data
POST {{baseUrl}}/tournaments
Content-Type: {{contentType}}

{
  "name": ""
}

###
